### ISSUE TITLE
Possible Cheaters error

### ISSUE THREAD

**Issue by DON-IDE** [HDInnovations/UNIT3D-Community-Edition#1006]
When i go to Possible Cheaters i get this error:

Call to a member function toDayDateTimeString() on null (View: /home/nginx/domains/mydomain.com/public/resources/views/Staff/cheater/index.blade.php) {"userId":3,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Call to a member function toDayDateTimeString() on null (View: /home/nginx/domains/mydomain.com/public/resources/views/Staff/cheater/index.blade.php) at /home/nginx/domains/mydomain.com/public/resources/views/Staff/cheater/index.blade.php:59)

I am on version 2.2.7

**Comment by HDVinnie** [comment]
This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.

**Comment by HDVinnie** [comment]
@DON-IDE are you still experiencing this error? If so can you please provide more info by answering the following. Have you manually created any users in your database? Did you import users from another codebase?

I ask because the error is for this line. `{{ $cheater->user->created_at->toDayDateTimeString() }}`

So `Call to a member function toDayDateTimeString() on null ` is saying that the `created_at` column is `null` for said user which is not possible with UNIT3D's System. Timestamps are always set on user register, etc. The only way it could have become null is if someone messed with the db manually, imported users from another codebase improperly or manually added a user to the DB improperly. 

One thing your could do is SSH to your server. CD to your project root. Run `php artisan tinker`. Then run `$brokenUsers = App\Models\User::whereNull('created_at')->get();` and see what it returns.

**Comment by nikosuk** [comment]
hi 
i am having same problem. ( i have imported my DB from old source).
i did what you suggest above, and i get many many lines like this ..:
 .....
       App\Models\User {#20276 …46},
       App\Models\User {#20277 …46},
       App\Models\User {#20278 …46},
        …11484
....
Any possible Fix ?

**Comment by HDVinnie** [comment]
If you ran `$brokenUsers = App\Models\User::whereNull('created_at')->get();` and got that many users back then whoever did your import didn't doo it right @nikosuk

**Comment by nikosuk** [comment]
i can imagine, :( 
is it salveageable now ?
