### ISSUE TITLE
[Feature] Anime, Manga, LN Clients

### ISSUE THREAD

**Issue by LastReaction** [HDInnovations/UNIT3D-Community-Edition#1113]
I see that you guys have begun a bit of work on Anime News Network, MangaUpdates, and a few other scrapers/clients for UNIT3D so that uploading manga would automatically pull information based on the provided IDs from those sites. I'd like to know if any assistance is needed in finishing these features, and will there be an addition for anime databases such as AniDB, MyAnimeList or AniList?

**Comment by Golumpa** [comment]
Personally I would suggest either AniList, AniDB or AnimeNewsNetwork over MyAnimeList for anime any day, MAL has really lost its touch lately.

- AniList - has a decent API with no need for a key while being pretty stable with no known downtime in recent. The API itself lets you decide what you need and what you don't by only requesting what is going to be used, pretty handy. The only thing going down for it is the **content isn't "as good"** aka. cover images as other sources.
- AniDB - is the best out of all of them for content but API would need heavy caching and limiting so you don't get **banned for 24 hours**. The API has everything you'd need except "staff" photos. you can use the character photo's but If you want the staff photo's you'd need to make another request for each staff member which is a little meh.
- AnimeNewsNetowrk - Has a public API and it doesn't ban on over requesting, it only gives a 503 error if you hit the rate limit. Its content isn't as good as AniDB but it's decent, **doesn't include staff images at all.**
- MyAnimeList - **Still doesn't have an official public API** even after like 2 years now and I also don't believe they are trustworthy anymore after all last time. They just don't seem to care for the community or for developers anymore. There is an unofficial API but I wouldn't want to rely on it as a middle-man on the offchance it breaks due to a site update, you're stuck without a working API.

**Comment by HDVinnie** [comment]
As of right now I am completely rewriting the meta data system. To start it will only have TMDB support but the structure and storing is much better. I have no problem adding Anime API as I planned to anyway. However I will not be adding multiple ones. The more API's and data merging the worse IMO. So will have to pick one and stick with it.

**Comment by LastReaction** [comment]
I see, that's good to hear! Your choice of only choosing one API for anime is fair enough. We recommend you use AniList then, its the best option out of all of them in terms of an API and covers all bases: anime, manga and light novels are all stored in their database, so you can use their API for all 3 of them.

**Comment by Golumpa** [comment]
So for now, would it be worth looking into the API or to wail till you have rewritten the meta data system to not have to do things twice?

For me it really depends on how long you think it's going to be till you work on rewriting the meta data system.
