### ISSUE TITLE
[Bug] Forum post tipping does not work, or tips unrelated post instead

### ISSUE THREAD

**Issue by shlandturtle** [HDInnovations/UNIT3D-Community-Edition#1193]
**Describe the bug**
Trying to tip a users post on forum does not do anything (FF) or alternatively the tipper gets redirected to another random post and tip goes to that instead (Chrome and derivatives). Seems like the ID's are somehow mixed up now.
For example topics/91?page=7#post-1175 redirects to and tips topics/13?page=1#post-91
This problem has been introduced during the last 62 commits.

**To Reproduce**
1. Go to a random post
2. Click on Tip This Poster
3. Nothing happens, or alternatively another post elsewhere gets tipped.

**Expected behavior**
Tip working and tipping the correct post.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7 (on commit 95033bd100e5cfc7d64f2df0f6340671de091646)
- Laravel Version: 6.17.0
- PHP Version: 7.4.2
- Database Driver & Version: mysql 5.7.29
- Web Server Driver & Version: nginx  1.15.8
- OS Driver and Version: Ubuntu 18.04

**Desktop (please complete the following information):**
 - OS:
 - Browser: Firefox 73, Chrome 80.0, Edge 80.0
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
This is linked to https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1192#issuecomment-593559196

**Comment by shlandturtle** [comment]
This was introduced in PR #1185 
This is caused by passing topic id in resources/views/forum/topic.blade.php#L48 and using that ID to look for post in app/Http/Controllers/BonusController.php#L489
Hence a post that has id of the topic you make a tip in gets tipped.
An easy fix would be to change BonusController.php line 489 to:
$post = Post::with('topic')->findOrFail($request->input('post'));
Proper fixing requires specifying the post in topic.blade.php and passing the correct ID, but this is beyond my skills.

**Comment by cbj4074** [comment]
Ahh, indeed, that change in https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/8e569dd8d439e84618417659dbc52d295a4bf434/app/Http/Controllers/BonusController.php#L489 seems to be the cause.

As I recall, I added the `$id` there because the route is defined as `'/posts/{id}/tip_poster'`, but didn't use the `id` anywhere within the controller method. I thought that was a mistake, but now realize that I changed the behavior. My bad!

**Comment by shlandturtle** [comment]
@HDVinnie 
PR #1229 did not fully resolve this issue. Currently the starting post is tipped, regardless of what post you make the tip for. Topic blade and BonusController logic works right, so I think the issue might be in helper.js. However, solving this further seems to be above my head.
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/resources/js/unit3d/helper.js#L794

**Comment by cbj4074** [comment]
Don't we just need to revert that one line that I changed?

If we do that, we should also eliminate the unused `{id}` parameter from the route definition (just because it's confusing to have it but not use it anywhere).

So, basically, do this?

```php
/**
 * Tip Points To A Poster.
 *
 * @param \Illuminate\Http\Request $request
 *
 * @return \Illuminate\Http\RedirectResponse
 */
public function tipPoster(Request $request)
{
    $user = $request->user();

    if ($request->has('post') && $request->input('post') > 0) {
        $post = Post::with('topic')->findOrFail($request->input('post'));
        $poster = User::where('id', '=', $post->user_id)->firstOrFail();
    } else {
        abort(404);
    }

    // ...
}
```

**Comment by cbj4074** [comment]
I finally had take time take a closer look at this, and fundamentally, the issues are as follows:

1. As I noted previously, the route requires an `{id}` parameter that intends to represent the `Post` ID, but it's never used in the controller method, and should therefore be removed from the route definition entirely.
2. Accordingly, the same parameter should be removed from https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/dd166ff4e2b75a5e0f1a28541d2539dc17e35946/resources/views/forum/topic.blade.php#L139 . It simply isn't necessary, because as noted above, it's never used, and only causes confusion. Rather, the `Post` ID is passed as a hidden parameter in the form that is constructed dynamically in JS at https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/dd166ff4e2b75a5e0f1a28541d2539dc17e35946/resources/js/unit3d/helper.js#L808 .

I'll address these changes and push a PR.

**Comment by cbj4074** [comment]
@shlandturtle When it's convenient, can you pull from `master` and see if this is fixed at this point?
