### ISSUE TITLE
[Feature] BitTorrent v2 (BEP 52) support

### ISSUE THREAD

**Issue by X-Coder264** [HDInnovations/UNIT3D-Community-Edition#1435]
libtorrent v2 has just been released with BitTorrent v2 support -> https://blog.libtorrent.org/2020/09/bittorrent-v2/

It'd be nice if the tracker would support it.

I've implemented it on my tracker (which is just my pet project):

https://github.com/X-Coder264/tracker/blob/master/app/Http/Controllers/AnnounceController.php
and tests
https://github.com/X-Coder264/tracker/blob/master/tests/Feature/Http/Controllers/AnnounceControllerTest.php

Hopefully this "example" can help to somewhat reduce the needed development time for the feature.

**Comment by HDVinnie** [comment]
Thanks. Ill defiantly have to look over the change log to see all the changes. Probably won't be for awhile though as Im already deep in refactors and another project.

**Comment by Rhilip** [comment]
It's may Too Early to support BEP 52 though it's Last-Modified at 2017-08-31,
And I do think we need two or more years to wait for this feature in tracker side.

At this moment, No Bittorrent client support this feature, even [arvidn/libtorrent v2](https://github.com/arvidn/libtorrent/releases/tag/2.0) released at 2020-09-07 (just 7 days ago). 

And:

1. There are still many user use Bittorrent client like uTorrent 1.x or uTorrent 2.x ( still it's not safe now), They may not update their client. It means we need a v1-and-v2 compatibility for tracker and mainly for torrent update controller.
2. Cut SHA-256 infohash from 32 bytes to 20 bytes (SHA-1 compatibility) for announce may cause extra hash collision in a private site and we may need another database field to store the raw sha-256 infohash.

**Comment by X-Coder264** [comment]
> It's may Too Early to support BEP 52 though it's Last-Modified at 2017-08-31,
> And I do think we need two or more years to wait for this feature in tracker side.

I don't see why is there a need to wait anything (let alone years) in order to implement this?

> 
> At this moment, No Bittorrent client support this feature, even [arvidn/libtorrent v2](https://github.com/arvidn/libtorrent/releases/tag/2.0) released at 2020-09-07 (just 7 days ago).

Yes, I opened this exactly because libtorrent v2 got released, which means that the first clients with BitTorrent v2 support are gonna start coming in half a year (or even earlier).

> 
> And:
> 
>     1. There are still many user use Bittorrent client like uTorrent 1.x or uTorrent 2.x ( still it's not safe now), They may not update their client. It means we need a v1-and-v2 compatibility for tracker and mainly for torrent update controller.

Yes, and special attention needs to be paid to tracking the traffic for hybrid torrents where the client can announce in both swarms (v1 and v2).

> 
>     2. Cut SHA-256 infohash from 32 bytes to 20 bytes (SHA-1 compatibility) for announce may cause extra hash collision in a private site and we may need another database field to store the raw sha-256 infohash.

I haven't seen the need to store the raw SHA-256 (yet).

**Comment by Rhilip** [comment]
After full read about BEP0052 and the announcement from libtorrent's blog.
And I saw some pr for qBittorrent to support libtorrent v2 's feature. 
So maybe you are right, wo can prepare this feature.

I still have some question ( or maybe I didn't full understand your last reply since poor english, hhhh. )

> Yes, and special attention needs to be paid to tracking the traffic for hybrid torrents where the client can announce in both swarms (v1 and v2).

From libtorrent, I find it always announce the first 20 bytes info_hash (as spec description), that means if torrent is a hybrid torrent, it will announce `'&info_hash=' + substr(hash('sha256', $dict['info']),0,20)` (in PHP format), else it will use the v1 info_hash like `'&info_hash=' + sha1($dict['info'])`.

> ref: https://github.com/arvidn/libtorrent/blob/867cf863f21747f2df7290df81a8d6a57a4d0992/include/libtorrent/info_hash.hpp#L105-L110

So if a hybrid torrent's hash information like 
```
v1 infohash 58485c1b6dc09d84da68d37272c80d7254bcb47e
v2 infohash 1560874ef639960aafaea8cf042213dc65bf3d6f32f55bdf4dec8eec865fe058
```
Should we consider about the infohash `1560874ef639960aafaea8cf042213dc65bf3d6f` for a completely different v1-only torrent, since we may not store the raw SHA-256, and a sha1 result may be conflict with first 20 bytes SHA-256 infohash. (though I don't know it will happened or not)

--------------------------

The other question:

3. Should we reject the v2-only torrent for client backward compatible? ( That means we only accept the v1 and v2-compatibility torrent.) 

4. Add this feature seems only affect the torrent upload (when Tracker verify torrent, get info_hash for torrent and store it), So What has changed in AnnounceController?

--------------------------

About add this feature:

I review the code, and I think we should focus in `class App\Helpers\{Bencode,TorrentTools}`. 
However some method in class Bencode seems duplicate, like:
  - Bencode::get_infohash   TorrentTools::getTorrentHash
  - Though Bencode support bdecode_file() method, there still have code like `$dict = Bencode::bdecode(\file_get_contents(\getcwd().'/files/torrents/'.$torrent->file_name));`
 
The advise are:
  - Move method Bencode::{get_infohash, get_meta} to TorrentTools, keep class Bencode as pure bencode library.
  - Make TorrentTools support v2 torrent.

And I'm happy to open a branch to test this feature in UNIT3D.

**Comment by X-Coder264** [comment]
> 
> 
> So if a hybrid torrent's hash information like
> 
> ```
> v1 infohash 58485c1b6dc09d84da68d37272c80d7254bcb47e
> v2 infohash 1560874ef639960aafaea8cf042213dc65bf3d6f32f55bdf4dec8eec865fe058
> ```
> 
> Should we consider about the infohash `1560874ef639960aafaea8cf042213dc65bf3d6f` for a completely different v1-only torrent, since we may not store the raw SHA-256, and a sha1 result may be conflict with first 20 bytes SHA-256 infohash. (though I don't know it will happened or not)

I don't have that collision problem due to this:

https://github.com/X-Coder264/tracker/blob/976341fffe781af051468de3646f0ff9bf7eb83f/app/Services/TorrentUploadManager.php#L85-L108

It's a protection against peer leaking attacks and due to it the info hash is an unique column in my DB -> https://github.com/X-Coder264/tracker/blob/976341fffe781af051468de3646f0ff9bf7eb83f/database/migrations/2017_09_03_183153_create_torrent_info_hashes_table.php#L18

Generally speaking there shouldn't be a problem with allowing `1560874ef639960aafaea8cf042213dc65bf3d6f` for a completely different v1 torrent.

> 
> The other question:
> 
>     1. Should we reject the v2-only torrent for client backward compatible? ( That means we only accept the v1 and v2-compatibility torrent.)
> 

I don't think we should. The user should see a message instead when he opens a v2 only torrent on the tracker that unless he has a v2 compatible client he won't be able to download the torrent.

>     2. Add this feature seems only affect the torrent upload (when Tracker verify torrent, get info_hash for torrent and store it), So What has changed in AnnounceController?

Not only the code in announce controller changes, but the DB table structure too. Info hash can no longer be a column on the torrent table, instead it must be a new table and similarly this is true for the peers table too (one peer can now be a peer in two different swarms (one for v1 and one for v2 swarm). Also the code in announce controller now must take into consideration possible race conditions when the client announces the (almost) same traffic with two announce requests at the "same" time (one for v1 info hash, one for v2 info hash).

**Comment by HDVinnie** [comment]
@Rhilip contributions are always welcome. Thank you.

@X-Coder264 I have also reviewed the BEP in full and your code. Hybrid torrents is what had me kind of confused but with your latest comments I get it now. Thank for breaking it down.

**Comment by Rhilip** [comment]
1. Add a extra field like `entropy` or other name in `info` dict is best solution for info_hash conflict problem.
   However It may cause other problem - `reupload`. 
   For example, If user download the torrent from our site and then upload this torrent, the old unique key in database may reject it (Or we can check it before insert into database). However, after add the `entropy` field, this method failed. And in your code, it always make new upload torrent unique (from do-while loop).

2. Add new DB table to record info_hash and it's ref to torrent table also seems `over-designed` in my mind.
   I think add a new column in torrent table to store the Truncated TorrentInfoHash (first 20 bytes) is enough. Then we can change the AnnounceController's from 

	```php
	        // Check Info Hash Against Torrents Table
	        $torrent = \cache()->get(\sprintf('torrent:%s', $info_hash)) ?? Torrent::withAnyStatus()
	                ->where('info_hash', '=', $info_hash)
	                ->first();
	```
	
	to something like:
	
	```php
	        // Check Info Hash Against Torrents Table
	        $torrent = \cache()->get(\sprintf('torrent:%s', $info_hash)) ?? Torrent::withAnyStatus()
	                ->where('info_hash', '=', $info_hash)
	                ->OrWhere('info_hash_v2', '=', $info_hash)   // `info_hash_v2` field store the first 20 bytes for sha256 infohash
	                // -> OrWhere('info_hash_v2', 'like', $info_hash . '%')  // if we store the full sha256 infohash
	                ->first();
	```

	( though it may cause the same torrent cache twice via different info_hash

**Comment by X-Coder264** [comment]
> 
> 
>     1. Add a extra field like `entropy` or other name in `info` dict is best solution for info_hash conflict problem.
>        However It may cause other problem - `reupload`.
>        For example, If user download the torrent from our site and then upload this torrent, the old unique key in database may reject it (Or we can check it's info_hash exist status before insert into database). However, after add the random `entropy` field, this method failed. And in your code, it always make new upload torrent unique (from do-while loop).
> 

Yes, it's up to the tracker staff to check if the torrent is duplicate.

>     2. Add new DB table to record info_hash and it's ref to torrent table also seems `over-designed` in my mind.
>        I think add a new column in torrent table to store the Truncated TorrentInfoHash (first 20 bytes) is enough.

I don't think that it is `over-designed`.  If you add the v2 hash column to the current torrents table it means that the current info hash column must become nullable and the new v2 column must be nullable as well, which means that you'd have two nullable columns in the same table (for which you then need to add additional validation logic that at least one of those columns cannot be null in the app code) which can be avoided with a new table. And what will you do when v3 comes out? Add yet another nullable column?

**Comment by Rhilip** [comment]
However in UNIT3D, the info_hash column in torrents table is not *unique*, just index key in this column.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9efd3dd9325d20b2e458505248f257e247aafd3e/database/migrations/2017_12_10_020753_create_torrents_table.php#L32

And The unique promise is support by Laravel validator:

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/9efd3dd9325d20b2e458505248f257e247aafd3e/app/Http/Controllers/TorrentController.php#L1343-L1364

In this case, nullable design can be replace by default empty string if we don't use unique key in database level, and empty string don't break the DB rule and won't trouble our tracker since we always use `->where('info_hash', '=', $info_hash)->OrWhere('info_hash_v2', '=', $info_hash)` (see last commit) to find torrent by its info_hash.
