### ISSUE TITLE
[Enhancement] Allowing direct gifting of Bonus Points between members should be a Staff Option

### ISSUE THREAD

**Issue by TheRover404** [HDInnovations/UNIT3D-Community-Edition#1444]
We have had members gifting other members many 100,000's of BON points, this then means those recipients never have to share anything back as they can get effectively get anything they want for "free". 
As the User Group promotion is also tied to upload this can be artificially "fudged" by these users buying upload credit without actually having to share anything.
This leaves normal members who have to share to gain legitimate bonus points at a big disadvantage and leads to considerable resentment.

Leaving a small tip for an upload or forum post etc is acceptable and should remain.

Appreciate that on some sites it may not be considered a problem, so it should be a Staff decision to decide whether direct gifting between members is allowed (and maybe if it is allowed what the maximum gift should be) or to disable it completely.
 

**Describe alternatives you've considered**
No disable options are currently available

**Comment by werrpy** [comment]
Instead of removing the fun of BON gifting, you could solve the actual problem by adjusting the BON store prices and earnings rates; so people don't end up with 100,000 BON easily in the first place. For instance, if you divide all the earning rates by 10, then they can only gift 10,000's BON points.

Add more BON sinks to encourage spending. BON is useless for those with 100,000's.
