### ISSUE TITLE
[Bug] /dashboard/seedboxes: The MAC is invalid.

### ISSUE THREAD

**Issue by piratkongen** [HDInnovations/UNIT3D-Community-Edition#1607]
**Describe the bug**
When in Staff Area, clicking on 'Seedboxes' to view seedboxes, it throws error 500.

**Expected behavior**
Look seedbox list.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1
- Laravel Version: Ver. 8.21.0
- PHP Version: php8.0.0
- Database Driver & Version: 8.0.22-0
- Web Server Driver & Version: ubuntu0.20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280

**Stack error:**
```
`
The MAC is invalid. (View: /var/www/html/resources/views/Staff/seedbox/index.blade.php) {"userId":3,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): The MAC is invalid. (View: /var/www/html/resources/views/Staff/seedbox/index.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:199)
`
```

**Comment by HDVinnie** [comment]
@piratkongen this is not a bug. This is due to you changing your APP_KEY. Laravel's encryption services provide a simple, convenient interface for encrypting and decrypting text via OpenSSL using AES-256 and AES-128 encryption. All of Laravel's encrypted values are signed using a message authentication code (MAC) so that their underlying value can not be modified or tampered with once encrypted. So `The MAC is invalid` is due to you having data in your database that was encrypted using a different APP_KEY.
