### ISSUE TITLE
Groups menu

### ISSUE THREAD

**Issue by heisenberg06** [HDInnovations/UNIT3D-Community-Edition#1623]
**Describe the bug**
On the torrent page when I click on groups it takes you to a 500 error page

**To Reproduce**
1. Go to 'https://yourdomain.com/torrents'
2. Click on 'groupings'
3. error 500

**Expected behavior**
That the torrents were grouped by movies and quality.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.0.0
- Laravel Version: 8.20.1
- PHP Version: 8.0.0
- Database Driver & Version: 8.0.22
- Web Server Driver & Version: ubuntu 20.04.3
- OS Driver and Version: 

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version: 88.0.4324.104

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Is this an issue still as Im not able to replicate it.

**Comment by heisenberg06** [comment]
Hello, the problem continues.

**Comment by Oha-you** [comment]
Can't reproduce the issue anywhere:
- on the demo site https://unit3d.site/ (latest master)
- locally using version v5.2.0
- on a live tracker (thousands of torrents) using version v5.1.0

@heisenberg06 have you tried updating the engine to the latest version? Is the issue still there?
Maybe it's happening because of some wrong metadata, filename, etc.
More info is needed: check server's `error.log`. Just "error 500" is not enough. If there's a stack trace there, please copy it here. 

Otherwise, the issue can be closed.

**Comment by Oha-you** [comment]
@HDVinnie no reply or additional data in 2+ weeks, so the issue can be closed, IMO.
