### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by will1869** [HDInnovations/UNIT3D-Community-Edition#1662]
v5.20 ran the update in var/www/html php artisan git:update
agred and said yes to all the changes 

After updating be sure to run php artisan db:seed --class=TicketCategoriesTableSeeder and php artisan db:seed --class=TicketPrioritiesTableSeeder

ran them after now get error 503 service unavalible 

please help vinnie what will it cost for you to come in and fix

**Comment by HDVinnie** [comment]
This is not a BUG. 503 service unavalible means site is in maintenance mode which means your update process did not complete successfully without any warning or error.  Stop ignoring our guidelines. You made a bug report for something that is not a bug and didn't even fill out all the required info in the template....instead you deleted it....you wonder y your ignored. I already told you what you need to do if you want realtime support.....otherwise use the discussions and wait patiently for a response....
