### ISSUE TITLE
Error seedtime

### ISSUE THREAD

**Issue by savertori** [HDInnovations/UNIT3D-Community-Edition#1996]
**Describe the bug**

After changing the timezone, I started noticing the overuse of the database. Even going back to UTC and restarting the supervisor didn't do it. 

**Expected behavior**
Update seeding time without error 

**Screenshots**

**UNIT3D (please complete the following information):**
    UNIT3D Version:5.3.0
    Laravel Version:Ver. 8.43.0
    PHP Version:8.0.7
    Database Driver & Version:8.0.27
    Web Server Driver & Version:nginx
    OS Driver and Version:Ubuntu 20.4

**Desktop (please complete the following information):**
    OS:win10
    Browser:chrome
    Version:95

**Additional context**

Possible Fix?
Maybe reset seedtime?

**Comment by savertori** [comment]
https://0bin.net/paste/ZHbtzNTw#twnKA2HZsjgxCdozc3Sz4yIQWuhUS-o450vBeNWrak5

**Comment by HDVinnie** [comment]
> https://0bin.net/paste/ZHbtzNTw#twnKA2HZsjgxCdozc3Sz4yIQWuhUS-o450vBeNWrak5

1) This has nothing to do with changing your timezone.
2) Provide the error above the stack trace.
3) From the looks of the previous exceptions you're getting a `MySQL Error 1264: out of range value for column seedtime` on the history table. That column is a `$table->bigInteger('seedtime')->unsigned()->default(0);`. Meaning it's already a bigInteger and unsigned. The error is happening because you are exceeding the length of int datatype. 

With that being said IMO its clear someones client is sending bad data. There is no way it should be exceeded.
https://www.w3resource.com/mysql/mysql-data-types.php

**Comment by HDVinnie** [comment]
After changing back to UTC did you clear your cache? `php artisan optimize:clear`? 
Are you using OPCache?
Did you restart server?

**Comment by savertori** [comment]
Hi, Vinnie.

Thanks for your help.

I change back to UTC, run optime:clear and reboot server.

Its solved!
