### ISSUE TITLE
[Bug]notifications arrive anyway

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#3390]
### UNIT3D Version

7.2.0

### PHP & Platform

8.1.2 php  linux 20.04.1

### Laravel verion

Laravel     10.37.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

If I uncheck the notification I shouldn't receive it

### Description

deselected the notification to be notified when a user I follow uploads a torrent

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Following a user overrides notification setting. The whole point of the follow system is so you get notified when users your following upload something.

**Comment by Roardom** [comment]
I believe the issue here is actually that if the torrent is uploaded by a user with a group with the is_modo flag, then any user with a group with that flag will bypass the recipient's notification settings.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/1ea331a1cd88144e5b5aa93f86182f234b01d7d8/app/Models/User.php#L812-L813

Unfortunately, you can't just remove that logic because not all notifications should be changed.
