### ISSUE TITLE
Adding torrents to a client in a paused state effects 'Average seedtime' marker

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3618]
### UNIT3D Version

7.x.x

### PHP & Platform

8.1.2

### Laravel verion

9.2.3

### Have you done this?

- [ ] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

'Average seedtime' should only count torrents with 'Download' > 0 bytes and/or 'Seeded' with some value other than N/A.

### Description

Any torrent that says hello to the tracker, regardless of any data movement, or seedtime from cross seeded torrents, currently impacts the Average seedtime metric. It seems prudent to included torrents with Seeded value N/A, **_and_**, Download > 0 bytes, since even when downloading, the torrent is also seeding, in the sense that it makes what data it has, available to the userbase.

However, for torrents that merely handshacke with the tracker, for any myriad of reasons, without any data movement, or making any data available to the userbase, these torrents unnecessarily, and heavily, skew the Average Seedtime metric.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by Roardom** [comment]
Working as intended. Your site imported all history records from tbdev, and tbdev includes downloaded .torrent files in the history records as well as announce history, even if you never announced, so your average is calculated across the wrong data.

As soon as you announce a torrent, it is part of your average, regardless of if you start downloading it or complete it or not. You'd be skewing your average otherwise.
