### ISSUE TITLE
[Bug] - Migration error - stdClass::delete undefined

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#3829]
### UNIT3D Version

8.1.3

### PHP & Platform

PHP 8.3.7 Ubuntu 22.04.4 LTS

### Laravel verion

Laravel Framework 11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I'm trying to migrate a database from v6.3.0 to the latest Unit3d version

### Description

Getting migration errors

https://paste.centos.org/view/d1c12b05

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3829">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3829/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3829/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
Do you still have the logs? Can you paste them directly into the issue? Your link returns a 404 now.

**Comment by Roardom** [comment]
Many of the errors will unfortunately still be there.

I recall you having 5-6 different errors. I fixed 2 of them, but the other ones were related to Laravel's (imo very poor) decision of changing the migration syntax in version 11. It's nearly impossible to migrate the existing syntax to the new syntax because they basically make all their column modifications absolute where it used to be relative. E.g. before, when you changed a column from string to int, if the column was previously null, it would remain null. Now, laravel will set the column back to not null if you don't explicitly specify it when converting the string to int.

Theoretically it might be possible to take a schema dump after every migration until April 22 (the release before our laravel 11 update) using both Laravel 10 and Laravel 11 and see where the diffs between them differ. It would probably be the only way we could fix it.

The only other fix for your issue specifically (although a pita) would be to run all the migrations until April 22 on laravel 10, then upgrade to laravel 11, then continue the remaining migrations.

**Comment by Roardom** [comment]
See the linked PR I completed last night.

**Comment by Roardom** [comment]
jfyi in case you're running unstable in prod: #3995
